[workspace]
resolver = "2"
members = [
  "crates/htsvcf",
  "crates/htsvcf-core",
  "crates/htsvcf-napi",
]

[workspace.package]
version = "0.1.13"
edition = "2021"
license = "MIT"

[workspace.dependencies]
rust-htslib = { git = "https://github.com/brentp/rust-htslib", branch = "record-translate-plus-pub", features = ["libdeflate"] }
v8 = "142.2.0"
serde_v8 = "0.285.0"


[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
