[package]
name = "htsvcf"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "htsvcf"

[features]
default = []
static = ["htsvcf-core/static", "rust-htslib/static"]

[dependencies]
v8.workspace = true
rust-htslib.workspace = true
htsvcf-core = { path = "../htsvcf-core" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_v8.workspace = true
